//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnigKing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korzina()
        {
            this.Zakazs = new HashSet<Zakaz>();
        }
    
        public int ID { get; set; }
        public int ID_Polz { get; set; }
        public System.DateTime DateZakaz { get; set; }
        public decimal Sum { get; set; }
        public Nullable<decimal> Sale { get; set; }
        public int ID_Status { get; set; }
        public int SrokVidach { get; set; }
        public Nullable<int> Kod { get; set; }
    
        public virtual Polz Polz { get; set; }
        public virtual StatusZakaz StatusZakaz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakazs { get; set; }
    }
}
