//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnigKing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlEntities : DbContext
    {
        public GlEntities()
            : base("name=GlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korzina> Korzinas { get; set; }
        public virtual DbSet<Polz> Polzs { get; set; }
        public virtual DbSet<PostavkaTovara> PostavkaTovaras { get; set; }
        public virtual DbSet<Proizvoditel> Proizvoditels { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusTovara> StatusTovaras { get; set; }
        public virtual DbSet<StatusZakaz> StatusZakazs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tovar> Tovars { get; set; }
        public virtual DbSet<Zakaz> Zakazs { get; set; }
    }
}
